[package]
name = "dissyssym-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.18.2", features = ["full"] }
async-trait = "0.1.53"
pathfinding = "3.0.12"
